name: CICD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  cache: 
    runs-on: ubuntu-latest 
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
  dependencies:
    runs-on: ubuntu-latest  
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
  test: 
    runs-on: ubuntu-latest 
    - name: Run test suite
      run: composer run-script test