name: Deploy

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code 
      uses: actions/checkout@v4
    - name: Validate composer.json and composer.lock
      run: composer validate --strict  
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test
      run: | 
        chmod +x vendor/bin/phpunit
        composer run-script test
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Get repository code 
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd anastmp0.beget.tech/public_html
            git pull origin main
            systemctl restart nginx
      
